name: Monthly US Debt Pipeline

# Give the token permission to publish releases
permissions:
  contents: write

on:
  schedule:
    # 2 PM UTC on the 2nd of every month
    - cron: '0 14 2 * *'
  workflow_dispatch:

jobs:
  run-debt-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # Pass the secret via env, not by editing your code
      - name: Run debt pipeline
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          python - << 'PY'
          import os, subprocess, sys
          # If your script already reads from env, just call it:
          #   python debt_pipeline.py
          #
          # Otherwise, pass it in explicitly:
          os.environ["FRED_API_KEY"] = os.getenv("FRED_API_KEY","")
          # Import and run your pipeline script
          import runpy
          runpy.run_path("debt_pipeline.py", run_name="__main__")
          PY

      - name: Upload results as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debt-pipeline-results-${{ github.run_number }}
          path: |
            us_debt_components_analysis.csv
            economic_data.db
            debt_pipeline.log
          retention-days: 90

      - name: Create release with data (optional)
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: data-${{ github.run_number }}
          name: Debt Data - ${{ github.run_number }}
          files: |
            us_debt_components_analysis.csv
            debt_pipeline.log
          body: |
            Automated debt pipeline run completed successfully.

            Run id: ${{ github.run_id }}
            Run number: ${{ github.run_number }}
